Add support for HiHome radiator thermostat
dresden-elektronik/deconz-rest-plugin pull request #4087
Opened 2021-01-03 13:58 UTC by KPWhiver

This PR adds support for the HiHome (discussed here: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3922). It also includes some fixes for the Saswell SEA801 radiator thermostat.

2021-01-03 14:22 UTC, Smanar commented
- Enable the defaut response for all tuya stuff (I have forget it, bad idea, provoke random bugs, realy important)
- Add support for 2 devices
- Add primary support for Tuya cluster time.
- Corrective for some Tuya schedule command.

2021-01-25 15:26 UTC, manup requested changes
Added some comments @Smanar can you please check them.

2021-01-25 15:26 UTC, manup commented on tuya.cpp
> +                    listday << t[dp-123];
This is dangerous in terms of maintenance if the code is extended later, the `dp - 123` index isn't bound checked.
Albeit due the switch case values a bound check is there, I'd prefer a more specific version. It took me a few minutes to realize that there is already an implicit array bound check and it's not a SEGV canditate.

```
const std::array<int, 7> t = {1,64,32,46,8,4,2};

if (dp < 0x007B || (dp - 0x007B) >= t.size())
{
    DPG_Printf(DBG_INFO, "Tuya unsupported daily schedule dp value: 0x%04X\n", dp);
    return; // bail out early
}
```

Note I replaced 123 by the equal hex value 0x007B to make it more clear where this lower bound offset (Sunday) comes from.

2021-01-25 15:26 UTC, manup commented on tuya.cpp
> +                        heatSetpoint = (quint8) ((heatSetpoint16 / 10) & 0xff);
Always use C++11 casts instead old style C casts as they are nasty in terms of type safety and easily overlooked.

```cpp
hour = static_cast<quint8>((minut16 / 60) & 0xff);
minut = static_cast<quint8>((minut16 - 60 * hour) & 0xff);
heatSetpoint = static_cast<quint8>((heatSetpoint16 / 10) & 0xff);

```

2021-01-25 15:26 UTC, manup commented on tuya.cpp
> +
* Too much bit magic, use *QDataStream* instead;
* `QByteArray data` over shadows `quint32 data` from above;
* Always use camelCase instead snake_case when naming things, the whole code base is camel case.

```
QByteArray payload;
QDataStream stream2(&payload, QIODevice::WriteOnly);
stream2.setByteOrder(QDataStream::LittleEndian);

stream << timeNow;
stream << timeLocalTime;

```

2021-01-25 15:26 UTC, manup commented on tuya.cpp
> +bool DeRestPluginPrivate::SendTuyaCommand( const deCONZ::ApsDataIndication &ind, qint8 command, QByteArray data )
Don't add spaces before and after braces. &rarr; Consistency with the the rest of the code base.
Same goes for all other statements like if, for, ...

2021-01-25 15:26 UTC, manup commented on tuya.cpp
> +    task.req.setDstEndpoint(ind.srcEndpoint() );
Spaces...

2021-01-25 15:26 UTC, manup commented on tuya.cpp
> +    }
Use C++11 `static_cast<Type>(Value)`

2021-01-25 15:26 UTC, manup commented on tuya.cpp
> +        DBG_Printf(DBG_INFO, "Tuya debug 7");
Don't print generic debug messages, it doesn't say anything meaningful.

```
DBG_Printf(DBG_INFO, "Failed to send Tuya command 0x%02X data: %s\n", command, qPrintable(data.toHex()));
```

2021-01-25 19:18 UTC, Smanar commented
Still on it, pls do not merge yet.

2021-01-25 21:47 UTC, Smanar commented
@KPWhiver I have updated the code, if you have some time, to test it again ?

2021-01-25 21:57 UTC, manup commented
>It also includes some fixes for the Saswell SEA801 radiator thermostat.

Please also list the "some fixes" in the PR description so readers know what the PR fixes :)

2021-01-25 22:06 UTC, Smanar commented
From my memory it's from here > https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3922
Without the defaut response, some command was missing from the device, random bug, random commands.

2021-01-26 20:17 UTC, KPWhiver commented
Yes, which brings me to another problem, the HiHome thermostat is a whitelabel of the SEA802 thermostat, which means it should be implemented identically. Unfortunately it isn't which makes me strongly suspect that SEA802 support in deconz is actually not there yet. But I don't think it's wise to also fix that here, since I don't have a SEA802 to test it with.

I'll test the fixes.

2021-01-26 21:19 UTC, Smanar commented
@KPWhiver it s the model "_TYST11_KGbxAXL2" ?
If I remember this model need to mimic the  "_TYST11_zuhszj9s" model, so easy to see if something is missing in code. I have check it have less feature enabled (no window closed check for exemple), but thoses 2 devices are "friends"

2021-01-26 21:23 UTC, Smanar commented on database.cpp
> +                    sensor.modelId() == QLatin1String("88teujp") || // Tuya
Wiki page started > https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Tuya-devices-List

2021-01-26 21:59 UTC, KPWhiver commented
No it's the _TYST11_c88teujp model, it should be identical to the HiHome thermostat. 

I tried checking out this pull request and running it but when I do deconz won't startup properly, this is what I get in the logs:
```
Jan 26 22:24:08 server conmon[26980]: New 'server:0 (root)' desktop at :0 on machine server
Jan 26 22:24:08 server conmon[26980]:
Jan 26 22:24:08 server conmon[26980]: Starting applications specified in /etc/X11/Xvnc-session
Jan 26 22:24:08 server conmon[26980]: Log file is /root/.vnc/server:0.log
Jan 26 22:24:08 server conmon[26980]:
Jan 26 22:24:08 server conmon[26980]: Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /root/.vnc/passwd server:0 to connect to the VNC server.
Jan 26 22:24:08 server conmon[26980]:
Jan 26 22:24:11 server conmon[26980]: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Jan 26 22:24:11 server conmon[26980]: libpng warning: iCCP: known incorrect sRGB profile
Jan 26 22:24:11 server conmon[26980]: libpng warning: iCCP: known incorrect sRGB profile
Jan 26 22:24:11 server conmon[26980]: 22:24:11:993 HTTP Server listen on address 0.0.0.0, port: 8080, root: /usr/share/deCONZ/webapp/
Jan 26 22:24:12 server conmon[26980]: 22:24:12:014 CTRL. 3.27.2
Jan 26 22:24:12 server conmon[26980]: 22:24:12:049 ZCLDB init file /root/.local/share/dresden-elektronik/deCONZ/zcldb.txt
Jan 26 22:24:12 server conmon[26980]: 22:24:12:115 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin
Jan 26 22:24:12 server conmon[26980]: 22:24:12:119 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
Jan 26 22:24:13 server conmon[26980]: 22:24:13:355 COM check bootloader
Jan 26 22:24:13 server conmon[26980]: QObject::connect: Cannot queue arguments of type 'QTextBlock'
Jan 26 22:24:13 server conmon[26980]: (Make sure 'QTextBlock' is registered using qRegisterMetaType().)
Jan 26 22:24:13 server conmon[26980]: QObject::connect: Cannot queue arguments of type 'QTextCursor'
Jan 26 22:24:13 server conmon[26980]: (Make sure 'QTextCursor' is registered using qRegisterMetaType().)
Jan 26 22:24:13 server conmon[26980]: 22:24:13:367 COM detected application
Jan 26 22:24:13 server conmon[26980]: 22:24:13:398 Device firmware version 0x26660700 ConBee II
Jan 26 22:24:13 server conmon[26980]: 22:24:13:402 unlocked max nodes: 200
Jan 26 22:24:13 server conmon[26980]: 22:24:13:473 Device protocol version: 0x010C
Jan 26 22:24:13 server conmon[26980]: 22:24:13:481 new node - ext: 0x00212effff05412d, nwk: 0x0000
Jan 26 22:24:13 server conmon[26980]: 22:24:13:582 Current channel 15
Jan 26 22:24:13 server conmon[26980]: 22:24:13:598 CTRL ANT_CTRL 0x03
Jan 26 22:24:13 server conmon[26980]: 22:24:13:623 Device protocol version: 0x010C
Jan 26 22:24:13 server conmon[26980]: 22:24:13:671 Current channel 15
Jan 26 22:24:13 server conmon[26980]: 22:24:13:687 CTRL ANT_CTRL 0x03
Jan 26 22:25:11 server conmon[26980]: 22:25:11:808 Current channel 15
Jan 26 22:25:11 server conmon[26980]: 22:25:11:816 Device TTL 6671 s flags: 0x7
Jan 26 22:26:11 server conmon[26980]: 22:26:11:808 Current channel 15
Jan 26 22:26:11 server conmon[26980]: 22:26:11:816 Device TTL 6611 s flags: 0x7
Jan 26 22:27:11 server conmon[26980]: 22:27:11:807 Current channel 15
Jan 26 22:27:11 server conmon[26980]: 22:27:11:815 Device TTL 6551 s flags: 0x7
Jan 26 22:28:11 server conmon[26980]: 22:28:11:809 Current channel 15
Jan 26 22:28:11 server conmon[26980]: 22:28:11:817 Device TTL 6490 s flags: 0x7
Jan 26 22:29:11 server conmon[26980]: 22:29:11:808 Current channel 15
Jan 26 22:29:11 server conmon[26980]: 22:29:11:816 Device TTL 6430 s flags: 0x7
Jan 26 22:30:11 server conmon[26980]: 22:30:11:808 Current channel 15
Jan 26 22:30:11 server conmon[26980]: 22:30:11:816 Device TTL 6370 s flags: 0x7
Jan 26 22:31:11 server conmon[26980]: 22:31:11:808 Current channel 15
Jan 26 22:31:11 server conmon[26980]: 22:31:11:816 Device TTL 6310 s flags: 0x7
Jan 26 22:32:11 server conmon[26980]: 22:32:11:807 Current channel 15
Jan 26 22:32:11 server conmon[26980]: 22:32:11:815 Device TTL 6250 s flags: 0x7
Jan 26 22:33:11 server conmon[26980]: 22:33:11:809 Current channel 15
Jan 26 22:33:11 server conmon[26980]: 22:33:11:817 Device TTL 6189 s flags: 0x7
Jan 26 22:34:11 server conmon[26980]: 22:34:11:808 Current channel 15
Jan 26 22:34:11 server conmon[26980]: 22:34:11:816 Device TTL 6129 s flags: 0x7
Jan 26 22:35:11 server conmon[26980]: 22:35:11:809 Current channel 15
Jan 26 22:35:11 server conmon[26980]: 22:35:11:817 Device TTL 6069 s flags: 0x7
Jan 26 22:36:11 server conmon[26980]: 22:36:11:807 Current channel 15
Jan 26 22:36:11 server conmon[26980]: 22:36:11:815 Device TTL 6009 s flags: 0x7
Jan 26 22:37:11 server conmon[26980]: 22:37:11:809 Current channel 15
Jan 26 22:37:11 server conmon[26980]: 22:37:11:817 Device TTL 5949 s flags: 0x7
Jan 26 22:38:11 server conmon[26980]: 22:38:11:809 Current channel 15
Jan 26 22:38:11 server conmon[26980]: 22:38:11:817 Device TTL 5889 s flags: 0x7
Jan 26 22:39:11 server conmon[26980]: 22:39:11:809 Current channel 15
Jan 26 22:39:11 server conmon[26980]: 22:39:11:817 Device TTL 5828 s flags: 0x7
Jan 26 22:40:11 server conmon[26980]: 22:40:11:808 Current channel 15
Jan 26 22:40:11 server conmon[26980]: 22:40:11:816 Device TTL 5768 s flags: 0x7
etc ...
```

2021-01-26 23:38 UTC, Smanar commented
"_TYST11_c88teujp" no problem for this one, better integration it is exactly at same place than the one finishing by uhszj9s

I have already have this problem, in epoch code, the compiler don't give error message, but the code is not working.

2021-01-27 00:25 UTC, Smanar commented
@KPWhiver corrected, the code compile and work now, on the previous one, the REST API was missing if you look at deconz menu.

2021-01-28 14:07 UTC, KPWhiver commented
With the fixes, deconz now runs, and I can send commands to the thermostats. However, they do not send any temperatures back, only the valve state:
```
Jan 28 08:01:27 server conmon[4063]: 08:01:27:960 Tuya debug 4 : Address 0x60A423FFFE8E2CE7 Payload 00e96501000101
Jan 28 08:00:28 server conmon[4063]: 08:00:28:015 Tuya debug 5 : Status: 0 Transid: 233 Dp: 357 (0x01,0x65) Fn: 0 Data 1
Jan 28 08:00:28 server conmon[4063]: 08:00:28:015 Tuya debug 4 : Address 0x60A423FFFE8E2CE7 Payload 00e96501000101
Jan 28 07:59:27 server conmon[4063]: 07:59:27:966 Tuya debug 5 : Status: 0 Transid: 233 Dp: 357 (0x01,0x65) Fn: 0 Data 1
Jan 28 07:59:27 server conmon[4063]: 07:59:27:963 Tuya debug 4 : Address 0x60A423FFFE8E2CE7 Payload 00e96501000101
Jan 28 07:59:18 server conmon[4063]: 07:59:18:245 Tuya debug 5 : Status: 0 Transid: 233 Dp: 357 (0x01,0x65) Fn: 0 Data 1
Jan 28 07:59:18 server conmon[4063]: 07:59:18:245 Tuya debug 4 : Address 0x60A423FFFE8E2CE7 Payload 00e96501000101
Jan 28 07:58:12 server conmon[4063]: 07:58:12:956 Tuya debug 5 : Status: 0 Transid: 233 Dp: 357 (0x01,0x65) Fn: 0 Data 1
Jan 28 07:58:12 server conmon[4063]: 07:58:12:956 Tuya debug 4 : Address 0x60A423FFFE8E2CE7 Payload 00e96501000101
Jan 28 07:57:12 server conmon[4063]: 07:57:12:957 Tuya debug 5 : Status: 0 Transid: 233 Dp: 357 (0x01,0x65) Fn: 0 Data 1
Jan 28 07:57:12 server conmon[4063]: 07:57:12:956 Tuya debug 4 : Address 0x60A423FFFE8E2CE7 Payload 00e96501000101
Jan 28 07:56:12 server conmon[4063]: 07:56:12:960 Tuya debug 5 : Status: 0 Transid: 233 Dp: 357 (0x01,0x65) Fn: 0 Data 1
Jan 28 07:56:12 server conmon[4063]: 07:56:12:959 Tuya debug 4 : Address 0x60A423FFFE8E2CE7 Payload 00e96501000101
Jan 28 07:55:31 server conmon[4063]: 07:55:31:504 Tuya debug 5 : Status: 0 Transid: 233 Dp: 357 (0x01,0x65) Fn: 0 Data 1
Jan 28 07:55:31 server conmon[4063]: 07:55:31:504 Tuya debug 4 : Address 0x60A423FFFE8E2CE7 Payload 00e96501000101
Jan 28 07:55:12 server conmon[4063]: 07:55:12:303 Tuya debug 5 : Status: 0 Transid: 233 Dp: 357 (0x01,0x65) Fn: 0 Data 1
Jan 28 07:55:12 server conmon[4063]: 07:55:12:303 Tuya debug 4 : Address 0x60A423FFFE8E2CE7 Payload 00e96501000101
Jan 28 07:55:02 server conmon[4063]: 07:55:02:207 Tuya debug 5 : Status: 0 Transid: 233 Dp: 357 (0x01,0x65) Fn: 0 Data 1
```

This suggests that for some reason the default response is not send anymore.

2021-01-28 15:29 UTC, Smanar commented
Oup, big thx for tests, all was broken, all the code was bypassed on first test.

2021-01-29 15:47 UTC, KPWhiver commented
It has been running stable for a day now, everything seems to work

2021-01-29 19:26 UTC, ebaauw commented on database.cpp
> +                    sensor.modelId() == QLatin1String("88teujp") || // Tuya
@manup, @Smanar Why a Wiki page?  Or rather: why not a table in code, like I've done for the LIDL devices?
https://github.com/dresden-elektronik/deconz-rest-plugin/blob/f46e3321715f755a057c19992e51ce9cf6f01e35/de_web_plugin.cpp#L447-L460

2021-01-30 09:16 UTC, Smanar commented on database.cpp
> +                    sensor.modelId() == QLatin1String("88teujp") || // Tuya
To be more accessible ?
I think the table can be moved soon with that https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4301/files

2021-02-02 06:27 UTC, k3mpaxl commented
Hi @Smanar, 
Time synchronization is broken. Time responses are being sent, but the time displayed jumps randomly. I'll try to sniff the traffic and report back to you.

2021-02-02 15:50 UTC, Smanar commented
Ha :(
But I don't see a change with the version from the other issue ...

2021-02-02 20:00 UTC, k3mpaxl commented
The time syncronization is broken, the byte order in the response is wrong, but the header byte order is correct!

Client request:
![sniff-03](https://user-images.githubusercontent.com/2837689/106655104-38aa0400-6599-11eb-9ff9-06db088fbfb7.PNG)
Response with this implementation.
![sniff-04](https://user-images.githubusercontent.com/2837689/106655169-4fe8f180-6599-11eb-852a-4c5165730b4c.PNG)

It should look like this:
```
0000   08 04 60 19 a7 7c 60 19 b5 8c
```

2021-02-02 20:46 UTC, Smanar commented
Ha yes I m seing the modification

Before 

```
        //Add the "magic vlaue"
        data.append((qint8)(UnknowHeader & 0xff));
        data.append((qint8)((UnknowHeader >> 8) & 0xff));
        
        // Add UTC time
        data.append((qint8)((time_now >> 24) & 0xff));
        data.append((qint8)((time_now >> 16) & 0xff));
        data.append((qint8)((time_now >> 8) & 0xff));
        data.append((qint8)(time_now & 0xff));
        // Ad local time
        data.append((qint8)((time_local_time >> 24) & 0xff));
        data.append((qint8)((time_local_time >> 16) & 0xff));
        data.append((qint8)((time_local_time >> 8) & 0xff));
        data.append((qint8)(time_local_time & 0xff));
```

after
```
        //Add the "magic value"
        stream2 << UnknowHeader;
         // Add UTC time
        stream2 << time_now;
        // Ad local time
        stream2 << time_local_time;
```

Have done a change, if you can test it pls ? https://github.com/KPWhiver/deconz-rest-plugin/commit/86a64137cf9d8f08564aaa78906de298168071b1

2021-02-03 07:49 UTC, k3mpaxl commented
> 
> 
> Ha yes I m seing the modification
> 
> Before
> 
> ```
>         //Add the "magic vlaue"
>         data.append((qint8)(UnknowHeader & 0xff));
>         data.append((qint8)((UnknowHeader >> 8) & 0xff));
>         
>         // Add UTC time
>         data.append((qint8)((time_now >> 24) & 0xff));
>         data.append((qint8)((time_now >> 16) & 0xff));
>         data.append((qint8)((time_now >> 8) & 0xff));
>         data.append((qint8)(time_now & 0xff));
>         // Ad local time
>         data.append((qint8)((time_local_time >> 24) & 0xff));
>         data.append((qint8)((time_local_time >> 16) & 0xff));
>         data.append((qint8)((time_local_time >> 8) & 0xff));
>         data.append((qint8)(time_local_time & 0xff));
> ```
> 
> after
> 
> ```
>         //Add the "magic value"
>         stream2 << UnknowHeader;
>          // Add UTC time
>         stream2 << time_now;
>         // Ad local time
>         stream2 << time_local_time;
> ```
> 
> Have done a change, if you can test it pls ? [KPWhiver@86a6413](https://github.com/KPWhiver/deconz-rest-plugin/commit/86a64137cf9d8f08564aaa78906de298168071b1)

Time synchronization is now working fine! Thanks for the late change.

2021-02-03 16:59 UTC, Smanar commented
@k3mpaxl Thx to you ^^.
For information I have no tuya devices at all, all the code was done with helpfull guys like you, I realy can't do anything without you.

2021-02-07 20:05 UTC, manup requested changes
Next round, added a few comments.
In general I really like the new defines like DP_IDENTIFIER_THERMOSTAT_SCHEDULE_2
makes the code more readable :+1:

2021-02-07 20:05 UTC, manup commented on tuya.cpp
> +    else if (Dp_identifier == 0x6D)
Should the 0x6D be `DP_IDENTIFIER_THERMOSTAT_SCHEDULE_4`?

2021-02-08 10:58 UTC, manup commented
@KPWhiver  small note, I'll add my requested changes in a further PR to get the release ready. Mostly changes are related to code style so logic will be the same.

2021-02-08 11:00 UTC, merged