Update for Zemismart Chain Roller Shades Driver M515EGB (TS0601)
dresden-elektronik/deconz-rest-plugin pull request #4274
Opened 2021-01-25 18:22 UTC by Smanar

This device have 2 model, the wired one, router, and the battery one, end device.
This code code permit the inclusion for the battery powered one.

Not tested.

2021-02-15 15:50 UTC, manup requested changes

2021-02-15 15:50 UTC, manup commented on de_web_plugin.cpp
> +                (lightNode.manufacturer() == QLatin1String("_TZE200_xuzcvlku")) ) // Zemismart Chain Roller Shades Driver M515EGB (TS0601)
White space, parentheses ;)

otherwise fine to merge

2021-02-15 16:52 UTC, manup commented
Thanks, but git is still complaining conflicts, can you please sync the PR with master.

2021-02-15 20:04 UTC, Smanar commented
Done

2021-02-21 10:07 UTC, jscheurwater commented
@Smanar I'm pretty new here and have the DeconZ with Phoscon setup on my Raspberry PI. I just wanted to pair the Zemismart M515EGB (battery powered) Zigbee device to the Phoscon app.

Like I just read here, you made some kind of modifications to the DeconZ rest API to make it possible to include this device, right?

Can you please tell me how I can use your code modification on my Raspberry PI Deconz Phoscon setup? 
Is this an update I have to do manually or will this modification be in the next update of Deconz?

Thanks in advance!

2021-02-21 12:27 UTC, Smanar commented
It seem you are not alone with the problem.
We are making tries here > https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4223#issuecomment-782835076

2021-02-22 13:41 UTC, manup approved these changes

2021-02-22 13:41 UTC, merged