workaround for gledopto lights to recall scenes with ct
dresden-elektronik/deconz-rest-plugin pull request #4444
Opened 2021-02-18 17:18 UTC by pSpitzner

This is a naiv workaround for gledopto extended color lights, as described in #2364 

Gledopto extended color lights support setting color either as temperature `ct` or as `xy`.
Only if colors are set via `ct` will white leds be used in devices that support them. Otherwise, RGB leds are used.
This is problematic with scenes that (are supposed to) recall colors as temperatures.

Tested with a gledopto lightstrip, `GL-MC-001`, `Extended color light`

2021-04-13 05:08 UTC, domoritz commented
That's awesome. Thank you for working on a fix.

2021-04-30 10:57 UTC, Schorsch980 commented
Great news! Can't wait to see this merged! I was close to revert to the Hue Bridge... not anymore :)

2021-04-30 12:52 UTC, manup requested changes
Sorry took a while for reviewing the PR.

To be frank I'm not too thrilled by converting group casts into a series of unicasts since this can fill the APS queue surprisingly quickly. Later on a better scene controller will introduced to hopefully fix such cases as GLEDOPTO and IKEA in a more solid way https://github.com/dresden-elektronik/deconz-rest-plugin-v2/issues/5.

But I think this PR can be merged as workaround until the new scene controller arrives. I assume that the impact is not too bad since likely networks don't contain large numbers GLEDOPTO lights.

2021-04-30 12:52 UTC, manup commented on rest_groups.cpp
> +                    }
For consistency please stick to to the remaining code style

```
if (lightNode->manufacturer() == QLatin1String("GLEDOPTO") &&
    lightNode->type() == QLatin1String("Extended color light"))
{
    // pass, we update manually below
}
```

2021-04-30 12:52 UTC, manup commented on rest_groups.cpp
> +
Same here

```
if (lightNode->manufacturer() == QLatin1String("GLEDOPTO") &&
    lightNode->type() == QLatin1String("Extended color light") &&
    ls->colorMode() == QLatin1String("ct"))
{
}
```

2021-05-26 09:14 UTC, torbenmb commented
Is there any plan to merge this workaround in the release of deconz?
I would highly appreciate this as it might solve all issues I currently have with GLEDOPTO lights.

2021-07-04 21:55 UTC, arneeichhorn commented
Are there any news on this?

BTW: GL-S-007P and GL-G-001P seem to support Zigbee Scenes in my setup.
GL-C-008 doesn't.
Maybe it would be possible to set a list of model numbers on a settings page or something for which devices to use unicast calls?
So that devices like the GL-S-007P GU10 and GL-G-001P garden spots still can use the more performant Zigbee scenes?

2021-07-31 09:08 UTC, realwax commented
Hi,
I add myself to the request list of this fix as I intend to use the 2id glc008, too. I haven't found any other 5 channel rgb with cw and ww controller yet, that seems to be a better solution. Gledopto seems to be the only one vastly available.

2021-11-08 22:28 UTC, NathanSweet commented
I'm stuck with a Gledopto bulb that I can't use with DeCONZ.

2022-02-11 17:48 UTC, pSpitzner commented
Sorry for the long delay, I missed the github notifications.

I have fetched the upstream and followed the style of the ikea workaround [#4846](https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4846). This seems much cleaner and easier to remove once a better fix is available.

2022-04-24 20:42 UTC, poelzi commented
I was wondering why the gledopto light in general don't use the white leds for colors that are not fully saturated. The full part of the color should be substracted from the rgb part and mixed with both white leds. This makes much, much nicer colors. I wonder if this is a general problem with gledopto lights currently.

2022-06-01 07:02 UTC, MaxGramser commented
@Mimiix is there an update about this?

2022-06-01 21:01 UTC, Mimiix commented
@MaxGramser I don't do anything with pull requests. All I can do is forward it as @manup handles those

2022-09-06 11:07 UTC, merged