Added support for an other Revision of Orvibo Motion Sensor SN10ZW
dresden-elektronik/deconz-rest-plugin pull request #4585
Opened 2021-03-14 15:42 UTC by ninharp

Added support for an other unknown Revision of Orvibo Motion Sensor SN10ZW
I added new device in supported devices because it differs in MAC prefix and also in the vendor id, i added also the different model id and the slightly different manufacturer name.

Note that this sensor sends its feedback to endpoint 0x0A and not like normal to endpoint 0x01

2021-03-15 07:15 UTC, Mimiix commented
@ninharp Thanks for this contribution! Is there a git issue i can link?

2021-03-15 20:48 UTC, manup requested changes
Something is off with the indentation, is this already using all 4 spaces per indentation level?

2021-04-18 12:02 UTC, manup commented
Any news here in regard to requested changes?

2023-12-01 13:29 UTC, RangeMethod2 approved these changes

2024-02-05 11:59 UTC, manup commented
Closing due inactivity, for further process this device should be integrated via DDF.

2024-02-05 11:59 UTC, closed without merging