[subdevice] items_optional for Dimmable light
dresden-elektronik/deconz-rest-plugin pull request #7173
Opened 2023-08-12 22:18 UTC by Zehir

Part 10 of https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7155

2023-08-29 22:25 UTC, manup commented
Ha interesting, @ebaauw if we have a light which doesn't support `cap/on/off_with_effect` is it better to not have the item and implicitly treat it as `false`, or have it and explicitly set it to `false`?

2023-08-29 23:04 UTC, ebaauw commented
My idea was to include `capabilities` items only when the light supports the corresponding capability, similar to only including supported `config` items.  Not sure if that’s best, but it seems simpler and maybe cleaner to me.  On the other hand, making these mandatory would force people to think about them when creating a DDF.

Note that the `color` `capabilities` and `config` items don’t apply to a dimmable light, and shouldn’t even be optional.  DDF should overwrite the device type (to color temperature light or (extended) color light) when the device does support these.  Also the old ZHA color dimmable light should not be used in a DDF, in favour of (extended) color light.

2023-08-29 23:15 UTC, Zehir commented
Maybe we should add a third array with a list of forbidden attributes ?

2023-08-29 23:21 UTC, ebaauw commented
> Maybe we should add a third array with a list of forbidden attributes ?

That’s redundant if you have optional attributes.

2023-08-29 23:24 UTC, Zehir commented
> 

Or maybe a rule that say if there is the attribute `capabilities/color` you should not use type `$TYPE_DIMMABLE_LIGHT`

2023-08-30 16:06 UTC, ebaauw commented
Huh?  Either we specify mandatory and optional items, implying the rest are not allowed, or we specify mandatory and forbidden item, implying the rest are optional.  I don't see why we need to specify mandatory, optional, and forbidden.

Either we specify the items per device type, or the device types per item.  I don't see why we want to specify mandatory items per device type, but forbidden devices types per item.

2023-09-10 12:31 UTC, ebaauw requested changes
See also https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Mandatory-and-Optional-Items-for-Lights-Resources.

2023-09-10 12:31 UTC, ebaauw commented on devices/generic/subdevices/dimmable_light.json
>      "items": [
`state/reachable` should be mandatory.

2023-09-10 12:31 UTC, ebaauw commented on devices/generic/subdevices/dimmable_light.json
> +        "cap/color/capabilities",
Not for _Dimmable Light_.

2023-09-10 12:31 UTC, ebaauw commented on devices/generic/subdevices/dimmable_light.json
> +        "config/color/ct/startup",
Not for _Dimmable Light_.

2023-09-10 12:31 UTC, ebaauw commented on devices/generic/subdevices/dimmable_light.json
> +        "config/color/execute_if_off",
Not for _Dimmable Light_.

2023-09-10 12:31 UTC, ebaauw commented on devices/generic/subdevices/dimmable_light.json
> +        "cap/transition_block",
Not for _Dimmable Light_.

2023-09-10 17:05 UTC, ebaauw requested changes

2023-09-10 17:05 UTC, ebaauw commented on devices/generic/subdevices/dimmable_light.json
> +        "cap/groups_not_supported",
`cap/groups/not_supported`

2023-09-10 17:48 UTC, Zehir commented on devices/generic/subdevices/dimmable_light.json
>      "items": [
Done

2023-09-10 17:48 UTC, Zehir commented on devices/generic/subdevices/dimmable_light.json
> +        "cap/color/capabilities",
Removed

2023-09-10 17:48 UTC, Zehir commented on devices/generic/subdevices/dimmable_light.json
> +        "config/color/ct/startup",
Removed

2023-09-10 17:49 UTC, Zehir commented on devices/generic/subdevices/dimmable_light.json
> +        "config/color/execute_if_off",
Removed

2023-09-10 17:49 UTC, Zehir commented on devices/generic/subdevices/dimmable_light.json
> +        "cap/transition_block",
Removed

2023-09-10 17:49 UTC, Zehir commented on devices/generic/subdevices/dimmable_light.json
> +        "cap/groups_not_supported",
Fixed

2023-09-10 18:25 UTC, ebaauw approved these changes

2023-09-10 18:56 UTC, merged