DDF for Bosch Smoke Alarm II (#9)
dresden-elektronik/deconz-rest-plugin pull request #7354
Opened 2023-11-13 20:50 UTC by Finne75

* Create bsd-2-smoke-alarm.js

* Rename bsd-2-smoke-alarm.js to bsd-2-smoke-alarm.json

2023-11-13 20:59 UTC, Finne75 commented
Hu? Validation error for DDF code provided by the deCONZ GUI DDF editor?

2023-11-13 21:56 UTC, SwoopX requested changes

2023-11-13 21:56 UTC, SwoopX commented on devices/bosch/bsd-2-smoke-alarm.json
> +            "fn": "zcl"
This line's why the validator complains. We've recently decided to rename the function, it now should be `zcl:attr`

2023-11-13 21:56 UTC, SwoopX commented on devices/bosch/bsd-2-smoke-alarm.json
> +          "default": 0
You can remove the default here

2023-11-13 21:57 UTC, SwoopX commented
Really good DDF. One question though: does the device respond to arbitrary read requests without waking it up?

2023-11-14 11:28 UTC, Finne75 commented
> Really good DDF. One question though: does the device respond to arbitrary read requests without waking it up?

The device responds to read requests, e.g. to read a cluster via GUI. It does so at any time as far as I noticed.

2023-11-16 17:39 UTC, manup commented
@SwoopX PR looks good to me, ready to merge?

2023-11-16 18:26 UTC, SwoopX approved these changes

2023-11-16 18:27 UTC, SwoopX commented
@manup Yeah, all looking good. You could remove the `"awake": true` parts, as the device seems to be a light sleeper, but that's just a blemish 😉

2023-11-28 10:37 UTC, merged