DDF for SONOFF TRVZB Thermostat
dresden-elektronik/deconz-rest-plugin pull request #7357
Opened 2023-11-15 16:13 UTC by fox34

As discussed in #7334.

- Product name : TRVZB
- Manufacturer : SONOFF
- Model identifier : TRVZB

2023-12-11 22:39 UTC, SwoopX requested changes
Hi there,

I'm afraid, the DDF requires some significant changes to be considered. The suggested file would be barely functional.

2023-12-11 22:39 UTC, SwoopX commented on devices/sonoff/trvzb-thermostat.json
> +        {
The battery reading and checkin is missing:

```
       {
          "name": "config/battery",
          "awake": true,
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2;",
            "fn": "zcl:attr"
          },
          "read": {
            "fn": "none"
          }
        },
        {
          "name": "config/checkin",
        },
```

2023-12-11 22:39 UTC, SwoopX commented on devices/sonoff/trvzb-thermostat.json
> +          "name": "state/temperature"
The defaults for this item are tailored for temperature measurement sensors and hence, will not work here. Please replace it by the following:

```
          "name": "state/temperature",
          "refresh.interval": 3660,
          "parse": {
            "at": "0x0000",
            "cl": "0x0201",
            "ep": 1,
            "eval": "Item.val = Attr.val;",
            "fn": "zcl:attr"
          },
          "read": {
            "at": "0x0000",
            "cl": "0x0201",
            "ep": 1,
            "fn": "zcl:attr"
          }
```

2023-12-11 22:39 UTC, SwoopX commented on devices/sonoff/trvzb-thermostat.json
> +  "bindings": [
The battery binding is missing:

```
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 3600,
          "max": 43200,
          "change": "0x00000002"
        }
      ]
    },
```

2023-12-11 22:39 UTC, SwoopX commented on devices/sonoff/trvzb-thermostat.json
> +        }
Please add additional thermostat bindings

```
{
          "at": "0x0012",
          "dt": "0x29",
          "min": 1,
          "max": 3600,
          "change": "0x00000001"
        },
        {
          "at": "0x001C",
          "dt": "0x30",
          "min": 1,
          "max": 3600
        }
```

2023-12-11 22:39 UTC, SwoopX commented on devices/sonoff/trvzb-thermostat.json
> +          "change": "0x0000000A"
Please change the values to:

```
          "min": 60,
          "max": 300,
          "change": "0x00000064"
```

2023-12-11 22:39 UTC, SwoopX commented on devices/sonoff/trvzb-thermostat.json
> +        },
This item is not supported, so please remove.

2023-12-11 22:39 UTC, SwoopX commented on devices/sonoff/trvzb-thermostat.json
> +        },
Please investigate which modes are supported by the device. The code below must be amended according to the findings:

```
        {
          "name": "config/mode",
          "refresh.interval": 3660,
          "read": {
            "at": "0x001C",
            "cl": "0x0201",
            "ep": 1,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x001C",
            "cl": "0x0201",
            "ep": 1,
            "eval": "if (Attr.val == 0) { Item.val = 'off' } else if (Attr.val == 1) { Item.val = 'auto' } else if (Attr.val == 4) { Item.val = 'heat' };",
            "fn": "zcl:attr"
          },
          "write": {
            "at": "0x001C",
            "cl": "0x0201",
            "dt": "0x10",
            "ep": 1,
            "eval": "if (Item.val == 'off') { 0 } else if (Item.val == 'auto') { 1 } else if (Item.val == 'heat') { 4 };",
            "fn": "zcl:attr"
          },
          "default": "heat"
        },
```

2023-12-11 22:39 UTC, SwoopX commented on devices/sonoff/trvzb-thermostat.json
> +      },
In order to make use of the `config/mode` item, the following code must be added and contain the actually usable settings (see respetive item comment)

```
      "meta": {
        "values": {
          "config/mode": {"off": 0, "auto": 1, "heat": 4}
        }
      },
```

2023-12-11 22:39 UTC, SwoopX commented on devices/sonoff/trvzb-thermostat.json
> +          "default": 0
Please remove the default value and add `"refresh.interval": 3660` instead.

2023-12-11 22:39 UTC, SwoopX commented on devices/sonoff/trvzb-thermostat.json
> +        },
Please replace by the code below:

```
        {
          "name": "config/offset",
          "refresh.interval": 3660,
          "read": {
            "at": "0x0010",
            "cl": "0x0201",
            "ep": 1,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x0010",
            "cl": "0x0201",
            "ep": 1,
            "eval": "Item.val = Attr.val * 10;",
            "fn": "zcl:attr"
          },
          "write": {
            "at": "0x0010",
            "cl": "0x0201",
            "dt": "0x28",
            "ep": 1,
            "eval": "Item.val / 10;",
            "fn": "zcl:attr"
          },
          "range": [-250, 250],
          "default": 0
        },
```

2024-01-10 16:50 UTC, Smanar commented
@fox34 are you still here ?

2024-01-10 20:02 UTC, fox34 commented
I made the requested changes, however:

> Please investigate which modes are supported by the device.

How would I do this? The device can be toggled between automatic and manual operation (and turned off, obviously). Automatic mode can (only?) be configured in the "official" SONOFF app, which I cannot use because I do not own the SONOFF gateway.

2024-01-11 16:18 UTC, Smanar commented
>How would I do this? The device can be toggled between automatic and manual operation (and turned off, obviously). Automatic mode can (only?) be configured in the "official" SONOFF app, which I cannot use because I do not own the SONOFF gateway.

Yes, it's fine, just check wich one mode you can use on it.
From Z2M they are using same 

`.withSystemMode(['off', 'auto', 'heat'], ea.ALL, 'Mode of the thermostat')`

And they have too problem with the "auto" mode, it seem this device don't use zigbee classic request, and use instead a personnal one > https://github.com/Koenkk/zigbee-herdsman-converters/pull/6443

2024-01-14 21:16 UTC, SwoopX approved these changes
Looks ok for me wrt the requested changes, thanks!

2024-02-05 01:10 UTC, manup commented
So ready for merging? :)

2024-02-05 16:48 UTC, Smanar commented
For me yes, have checked again ,all @SwoopX remark are resolved.

2024-03-28 11:30 UTC, merged