fix lidl smart plug consumption value
dresden-elektronik/deconz-rest-plugin pull request #7361
Opened 2023-11-19 16:53 UTC by Pirionfr

multiply by 10 consumption

2023-11-28 12:21 UTC, manup requested changes

2023-11-28 12:21 UTC, manup commented on devices/lidl/hg08673.json
> +            "eval: "item.val = 10 * Attr.val"
Invalid JSON :) there is a missing quote after `"eval`

2023-11-28 20:10 UTC, SwoopX requested changes

2023-11-28 20:10 UTC, SwoopX commented on devices/lidl/hg08673.json
> +            "ep": 0,
Could you please set the endpoint here (to 1)?

2023-11-28 20:10 UTC, SwoopX commented on devices/lidl/hg08673.json
> +          "default": 0
The default can be safely removed, as it will be set already automatically. When removing, please do not forget the comma in the line above 😉

2023-11-28 20:10 UTC, SwoopX commented on devices/lidl/hg08673.json
> +          "refresh.interval": 300,
The refresh interval should be roughly 60 seconds larger than the max reporting interval of the attirbute. You have defined 360 max reporting, so it should be 420 up here.

As a side note, the vast majority of devices uses a max reporting interval of 300 secs and a respective refresh interval of 360.

2023-11-29 16:11 UTC, SwoopX approved these changes

2023-11-29 18:54 UTC, manup requested changes

2023-11-29 18:54 UTC, manup commented on devices/lidl/hg08673.json
>            "name": "state/consumption"
Small issue here, missing comma after `"state/consumption"`

2023-11-30 12:57 UTC, merged