Add DDF for Bosch Thermostat II 230V
dresden-elektronik/deconz-rest-plugin pull request #7575
Opened 2024-02-04 15:43 UTC by aSauerwein

copy/pasted the thermostat2.json and adapter for the wired versions.
changes:

   *  i removed the config/battery
   *  added state/valve with read&parse of 0x4020

open questions

  * I did not understand what the "bindings" are used for
  deconz-gui still shows the battery icon. don't know what needs to be changed to get that icon removed.
  * for state/valve I just used Item.val = Attr.val but I'm not sure if that correctly matches the percent valve opening
  * I cannot control the thermostat with phoscon web app. It just displays 40F and nothing changes, but it's working fine over homeassistant and rest api

fixes https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7553

2024-02-07 12:18 UTC, mattreim commented
Hello aSauerwein,

with this changes should be function the DDF:

1. Correction file name: "room_thermostat2_230V"
2. Add product name: "Room thermostat II 230V (BTH-RM230Z)"
3. Delete: Battery
4. Add: valve

[room_thermostat2_230V.json](https://github.com/dresden-elektronik/deconz-rest-plugin/files/14193597/room_thermostat2_230V.json)

2024-02-11 11:05 UTC, aSauerwein commented
hi @mattreim 
thanks! i imported your .json and it looks fine!

2024-02-11 12:04 UTC, mattreim commented
@aSauerwein check whether the device supports this cluster.

![poll_control_cluster](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/80219712/bccea4ba-c5b5-47cb-b65b-a32b943ca679)

2024-02-11 22:19 UTC, SwoopX requested changes
Just a few minors to catch up with 👍

2024-02-11 22:19 UTC, SwoopX commented on devices/bosch/room_thermostat2_230V.json
> +          "0x0001",
Please remove entry `0x0001` here, we do not have a battery powered device this time 😉

2024-02-11 22:19 UTC, SwoopX commented on devices/bosch/room_thermostat2_230V.json
> +          "0x0001",
Please remove entry `0x0001` here, we do not have a battery powered device this time 😉

2024-02-11 22:19 UTC, SwoopX commented on devices/bosch/room_thermostat2_230V.json
> +        },
As it has already been mentioned, this part should be removed, as it wouldn't work out based on the provided screenshot.

2024-03-21 20:14 UTC, SwoopX approved these changes
Should be good to go now, thanks!

2024-03-28 11:31 UTC, merged