DDF for Sonoff SNZB-06P
dresden-elektronik/deconz-rest-plugin pull request #7582
Opened 2024-02-08 21:23 UTC by lhering

The DDF as discussed in Issue #7369 and the general.xml changes for the light sensor.

2024-02-09 16:23 UTC, Smanar commented
Hello, there is some changes on recent version.
Try changing `"fn": "zcl`" by `"fn": "zcl:attr"`

2024-02-11 10:15 UTC, Smanar commented
Still a typo ^^

`"fn": "None"`

It's "none"

2024-02-11 10:33 UTC, lhering commented
Yey no errors :)

This is my first Pull Request, is there anything else I have to do?

2024-02-11 10:51 UTC, Smanar commented
NoNo it's fine ^^. Now just need to wait for validation.
Just a comment, 

```
          "refresh.interval": 4,
          "read": {
            "fn": "none"
          },
```

Both line are working together, the device normaly use the bind/report you have set at the end, and if and only if this one fail after the period "refresh.interval" deconz make a poll using the "read" line.
So we always use bigger value for "refresh.interval" but in this situation it's useless because you have disable the "read" line.
So for me, you can remove the refresh.interval, or use a bigger one with the "read" fonction.

For the 
```
         "refresh.interval": 30,
          "read": {
            "at": "0x2001",
            "cl": "0xfc11",
            "ep": 1,
            "fn": "zcl:attr"
          },
```

You haven't set bind/report at the end, it's an exotic cluster so perhaps not supported, so it mean every 30s deconz ask for the value.
Not a big problem as the device is powered, but if the bind/report is working better to use it, and set a bigger value for "refresh.interval" as security if it's not working.

```
{
  "bind": "unicast",
  "src.ep": 1,
  "cl": "0xfc11",
  "report": [
    {
      "at": "0x2001",
      "dt": "0x20",
      "min": 1,
      "max": 300,
      "change": "0x00000001"
    }
  ]
}
```

2024-02-11 14:28 UTC, manup commented
Hi please also use a JSON formatter like https://jsonformatter.org

2024-02-11 16:20 UTC, lhering commented
@Smanar Thanks, I've changed the parts
@manup The format should look better now

2024-02-11 18:49 UTC, Smanar commented
Lol a new problem
>The refresh interval (300 - 60 = 240) should be greater than the binding max refresh value (300) with a margin of 60 seconds

You have set the same time in the resfresh.interval, and on the bind/report, the device need to use the bind/report and not the refresh, so we set a bigger timing for the refresh.interval.

2024-02-11 19:00 UTC, SwoopX requested changes
Almost there, just some small things to amend from my perspective 👍

2024-02-11 19:00 UTC, SwoopX commented on devices/sonoff/snzb-06p.json
> +  "path": "/devices/snzb-06p.json",
Please remove the `path` stanza, as it is not necessary :)

2024-02-11 19:00 UTC, SwoopX commented on devices/sonoff/snzb-06p.json
> +          "change": "0x00000001"
As the datatype is discrete here, `"change": "0x00000001"` is superfluous. Therefore, please remove that line and do not forget about the comma one line above 🙂

2024-02-11 19:00 UTC, SwoopX commented on devices/sonoff/snzb-06p.json
> +          "refresh.interval": 300,
As the error suggests, the interval should be greater than the one you've chosen at the end of the DDF for attribute reporting. As you chose 300 seconds below, a value of 360 is recommended here.

2024-02-11 19:00 UTC, SwoopX commented on devices/sonoff/snzb-06p.json
> +        {
You might want to consider adding `config/delay` as well, as the device allows setting the interval when it changes from occupied to unoccupied via attribute 0x0020.

An example would be the Philips motion sensor:
https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/philips/sml001_motion_sensor.json

2024-02-11 19:00 UTC, SwoopX commented on devices/sonoff/snzb-06p.json
> +  "product": "SNZB-06P",
You might want to spend 2-3 additional words what kind of device that is 🙂

2024-02-11 19:00 UTC, SwoopX commented on devices/sonoff/snzb-06p.json
> +    },
AS the IAS Zone cluster does not seem to be used in any way, please remove this part.

2024-03-14 16:32 UTC, Smanar commented
@lhering there is still somes changes requested.

2024-03-14 20:16 UTC, lhering commented
I dont know whats mssing here. Maybe someone could help me what I have to do.

2024-03-15 15:39 UTC, Smanar commented
@lhering oups, sorry you are right.
@SwoopX all is ok for you ? If I m right all your requested changes are dones ?

2024-03-15 21:02 UTC, SwoopX commented
Yup, looks indeed like my remarks were all addressed. Thanks.

2024-03-15 21:02 UTC, SwoopX approved these changes

2024-03-16 19:12 UTC, ThiemeNL commented
@lhering could you please complete the PR? Thank you for your effort.

2024-03-16 19:24 UTC, Smanar commented
It's ok, the PR is complete ^^.

2024-03-28 11:33 UTC, merged

2024-12-25 21:11 UTC, LordGMM commented
![IMG_1101](https://github.com/user-attachments/assets/e7dd124a-862f-4878-a491-365f6a8d5d19)
Is there a chance to add those parameters to the ddf?

I d like to have two off my sensors to be within a longer range

2024-12-26 17:39 UTC, Smanar commented
Can try with the GUI, cluster 0x0406, attribute 0x0022
Or add to the DDF

```
        {
          "name": "config/sensitivity",
          "awake": true,
          "refresh.interval": 3600,
          "read": {
            "at": "0x0022",
            "cl": "0x0406",
            "ep": 1,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x0022",
            "cl": "0x0406",
            "ep": 1,
            "eval": "Item.val = Attr.val;",
            "fn": "zcl:attr"
          },
          "write": {
            "at": "0x0022",
            "cl": "0x0406",
            "dt": "0x20",
            "ep": 1,
            "eval": "Item.val",
            "fn": "zcl:attr"
          }
        },
```

2025-08-11 20:11 UTC, mantaalex commented
is it possible to set the sensitivity yet in home assistant or deconz app?

2025-08-13 16:26 UTC, Smanar commented
The code on my previous post have never be tested/added.