DDF for IKEA ASKVADER on/off switch
dresden-elektronik/deconz-rest-plugin pull request #7592
Opened 2024-02-10 21:30 UTC by mattreim

IKEA ASKVADER on/off switch:

![askvader_on_off_switch](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/80219712/b103f5a8-453d-4248-b9a0-4d7e1babc683)

2024-02-11 19:26 UTC, SwoopX requested changes
Thanks for raising this PR. Just some minors to address as far as I can tell.

However, as we do not have a dedicated device support request for this particular device, I need to judge on what I see here. No guarantee anything is missed but trusting it's complete 🙂

2024-02-11 20:09 UTC, mattreim commented on devices/ikea/askvader_on_off_switch
> +    }
Did I understand it correctly?

2024-02-11 20:20 UTC, mattreim commented on devices/ikea/askvader_on_off_switch
> +    }
In the DDF for "tradfri_control_outlet.json" it is exactly the same.

2024-02-11 21:03 UTC, SwoopX commented on devices/ikea/askvader_on_off_switch
> +    }
I'm afraid the attribute reporting configuration is still missing as mentioned above. After that, we should be good to go here.

2024-02-11 21:27 UTC, mattreim commented on devices/ikea/askvader_on_off_switch
> +    }
![bindings_1](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/80219712/ea0b6019-e7ea-43c6-a3f0-dfe0d0c589b7)

Ok?

2024-02-11 21:57 UTC, SwoopX commented on devices/ikea/askvader_on_off_switch
> +    }
The last few lines only, yes.

2024-02-11 22:01 UTC, mattreim commented on devices/ikea/askvader_on_off_switch
> +    }
360 or 300?

2024-02-11 22:29 UTC, mattreim commented
I hope it's right. thanks for the help.

2024-02-11 22:34 UTC, mattreim commented
Should I repair the Tradfri control outlet?

2024-02-12 21:00 UTC, SwoopX commented on devices/ikea/askvader_on_off_switch
> +    }
The interval for the reporting should be 300 instead of 360, otherwise, the validator will start complaining later 👍

2024-02-12 21:03 UTC, SwoopX commented
> Should I repair the Tradfri control outlet?

I'd probably apply the same reporting config also for this device. Simple deconz restart should be sufficient then.

2024-02-12 21:13 UTC, mattreim commented
> > Sollte ich die Tradfri-Steuersteckdose reparieren?
> 
> Ich würde wahrscheinlich dieselbe Berichtskonfiguration auch für dieses Gerät anwenden. Dann sollte ein einfacher Deconz-Neustart ausreichen.

I mean this: https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/ikea/tradfri_control_outlet.json

2024-02-12 23:17 UTC, SwoopX commented
> > > Sollte ich die Tradfri-Steuersteckdose reparieren?
> > 
> > 
> > Ich würde wahrscheinlich dieselbe Berichtskonfiguration auch für dieses Gerät anwenden. Dann sollte ein einfacher Deconz-Neustart ausreichen.
> 
> I mean this: https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/ikea/tradfri_control_outlet.json

Yeah, I know which device you meant, but maybe I did not (correctly) get what you intended to do?

2024-02-12 23:18 UTC, SwoopX approved these changes

2024-02-12 23:27 UTC, mattreim commented
1.  From:       "name": "state/on",
                     "refresh.interval": 5

     To:            "name": "state/on",
                     "refresh.interval": 360

2. From:         "bindings": [
                      {
                       "bind": "unicast",
                       "src.ep": 1,
                       "dst.ep": 1,
                       "cl": "0x0000"
                      },
                     {
                      "bind": "unicast",
                      "src.ep": 1,
                      "dst.ep": 1,
                      "cl": "0x0006"
                      }

   To:             "bindings": [
                    {
                       "bind": "unicast",
                       "src.ep": 1,
                       "dst.ep": 1,
                       "cl": "0x0000"
                     },
                     {
                       "bind": "unicast",
                       "src.ep": 1,
                       "dst.ep": 1,
                       "cl": "0x0006"
                       "cl": "0x0006",
                       "report": [
                         {
                           "at": "0x0000",
                           "dt": "0x10",
                           "min": 1,
                           "max": 300
                         }

2024-02-13 19:58 UTC, SwoopX commented
Ah, you want to change the other DDF accordingly 🙂 

Well, if you have the device and can test it, feel free. But watch out the duplicate cluster entry you have accidentally in there.

2024-02-13 20:10 UTC, mattreim commented
Ok

2024-03-28 11:34 UTC, merged